// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Website.Models;

[Table("uploadfile")]
public partial class mFile
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Column("filepath")]
    [StringLength(255)]
    [Unicode(false)]
    public string Filepath { get; set; }

    [NotMapped]
    public IFormFile Files { get; set; }
}